### PR TITLE
upgrade ex_rlp

### PR DESCRIPTION
**Pull request by ayrat555**
- upgrade ex_rlp to the latest version

### CODE REVIEW

**Comment by ayrat555** [comment]
@hayesgm can you merge this changes and publish new version on hex.pm?

**Comment by hayesgm** [comment]
Thanks for bumping version, will do.

**Comment by ayrat555** [comment]
@hayesgm will you publish it on hex.om?

**Comment by hayesgm** [comment]
Yup, doing that now.

**Comment by hayesgm** [comment]
Done https://hex.pm/packages/merkle_patricia_tree/0.2.7. I also added you as an owner on hex.

**Comment by ayrat555** [comment]
Thank you!

**Pull request merged**
